// <auto-generated />
namespace Solution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pack_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pack_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201911021247286_pack_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
